### ISSUE TITLE
[PRF] problème d'initialisation après calcul avec paramètres avancés

### ISSUE THREAD

**Issue by mrouan** [LETG/madDog#105]
**Description du bug / Describe the bug**

Lorsque l'on choisi de faire un traitement sur les profils avec des paramètres avancés : 
- le calcul se fait bien la première fois avec les paramètres avancés définis
- si on modifie les paramètres, il ne sont pas pris en compte dans le calcul
- si on souhaite afficher un autre profil (PRF2 par exemple) le menu de choix des dates ne s’initialise pas et il est alors impossible d'afficher les profils ni de lancer le traitement

Si les paramètres par défaut sont utilisés le problème ne se produit pas et il est possible de changer de profil.
En revanche si un traitement a été lancé sur un profil (PRFn), les dates du second profils choisi (PRFm) ne sont pas sélectionnées par défaut, elles sont bien sélectionnées si on choisi un 3ème (puis 4èeme, etcc..) profil

**Comment by Gaetanbrl** [comment]
Disponible sur la branche develop @mrouan.
