### ISSUE TITLE
[GENERAL] - Emprise de départ non prise en compte

### ISSUE THREAD

**Issue by Gaetanbrl** [LETG/madDog#107]
## Environnement

URL : https://portail.indigeo.fr/mviewer_preprod/?config=apps/maddog.xml#
BRANCHE : develop

## Description

Sur develop, l'emprise n'est pas bien calculée. C'est en effet l'emprise du XML qui s'affiche au démarrage.

![image](https://github.com/LETG/madDog/assets/16317988/41e8258d-f035-4040-9e29-a48d1bdc8f78)

**Comment by Gaetanbrl** [comment]
## Analyse

Il semble en effet qu'au chargement de l'addon, la méthode n'est pas appelée correctement :

https://github.com/LETG/madDog/blob/develop/mviewer/maddog/addons/maddog/maddog.js#L38

il manque les parenthèse pour avoir : 

`.then(v => setZoomToCommunes);`

## Test

L'emprise semble mieux se charger selon la zone attendue :

![issueEmprise](https://github.com/LETG/madDog/assets/16317988/2bb02ce1-261d-424d-8d24-3c34ebabde4b)

**Comment by mrouan** [comment]
le problème d'emprise est corrigé
