### ISSUE TITLE
DATA IMPORT - problème de date

### ISSUE THREAD

**Issue by mrouan** [LETG/madDog#59]
**Description du bug / Describe the bug**

Les dates affichées (légendes et selection) sont décalées d'un jour par rapport aux données importées (CSV)

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://gis.jdev.fr/mviewer/?config=apps/maddog.xml#
2. Cliqué sur plage du Vougot / TDC
3. affiché 10/06/1952 pour 11/06/1952 (etc...

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: win10
 - Navigateur / browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 101.0

**Comment by Gaetanbrl** [comment]
Les données sur la cartes sont récupérées en WFS via le GeoServer qui indique bien une date au 10/06/1952.

1. Voici l'appel complet VOUGOT : 

https://gis.jdev.fr/geoserver/maddog/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=maddog:tdc&outputFormat=application/json&CQL_FILTER=idsite=%27VOUGOT%27

2. Les données en base :

![image](https://user-images.githubusercontent.com/16317988/173312871-528176e9-97c3-4495-8f3f-eeef02b1719e.png)


On a donc un décalage réalisé par GeoServer qui retourne la date du `1952-06-11` en `1952-06-10Z`.

3. L'horaire sur le serveur est bonne : 

```
               Local time: lun. 2022-06-13 10:33:46 CEST
           Universal time: lun. 2022-06-13 08:33:46 UTC
                 RTC time: lun. 2022-06-13 08:33:47
                Time zone: Europe/Paris (CEST, +0200)
System clock synchronized: yes
              NTP service: n/a
          RTC in local TZ: no
```

**Comment by mrouan** [comment]
Cela ne viendrait il pas du format date en base ?
Faudrait-il lui préférer timestamp (with or without time zone) ?

**Comment by pierrejego** [comment]
Les données insérées en base sont bonnes, mais sans notion de timezone, c'est le geoserver qui passe en Z et le serveur n'étant pas en UTC il faut - 2h et passe donc à la date de la veille 
https://gis.stackexchange.com/questions/413474/geoserver-subtracts-time-difference-to-utc-from-date-stored-in-postgresql

Si je met en timestamp dans la base de données, les données sont aussi visible en timestamp dans le mviewer .

Les données sont insérées depuis le csv via le VRT en base de données puis exposé par geoserver.

Je n'ai pas de solution simple pour le moment : 
- Soit on passe en timestamp dans le VRT et en base( a tester il faut passer du format YYYY-MM-DD en timestamp) et en base et il faut faire un tri côté front (vérifier si ça rajoute pas de latence)
- Soit on passe le serveur en UTC
- Soit on utilise les données stocké en base pour les dates via le postgrest, mais il faut s'assurer qu'il retrouve bien ses petits en appelant le geoserver (

La dernière solution me semble la mieux mais elle est a tester

**Comment by pierrejego** [comment]
@mrouan vérifie si il est possible de passer le serveur geoservice en UTC

**Comment by mrouan** [comment]
résolu en ajoutant les paramètres d'environnement suivants dans l'instance tomcat :
`                -Duser.timezone=Europe/Paris \
                -Dorg.geotools.localDateTimeHandling=true \`
