### ISSUE TITLE
GENERAL - problème de légende

### ISSUE THREAD

**Issue by mrouan** [LETG/madDog#73]
**Description du bug / Describe the bug**

Les traits de légende ne s'affichent pas pour certaines dates

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://portail.indigeo.fr/mviewer/?config=apps/maddog.xml#
2. Cliquer sur "Plage du Vougot"
3. Cliquer sur "Trait de cote"
4. Naviguer dans le menu déroulant de choix de la date
5. Voir que rien certaines dates n'ont pas de trait de couleur
6. décocher ces dates et constater que le trait de couleur s'affiche

remarques : 
- ce ne sont pas les mêmes dates à chaque rechargement de la page (car ce ne sont pas les même couleur du au tirage aléatoire)
- sur la carte le TDC est bien affiché 
- dans la légende le TDC est bien affiché 
- une fois décoché le trait s'affiche systématiquement en noir

**Screenshots**

Si possible, une capture d'écran pour nous aider à voir le problème décrit.
![Capture2](https://user-images.githubusercontent.com/5336907/186867351-ff775364-31e7-4813-bfa9-70c541879341.PNG)
![Capture](https://user-images.githubusercontent.com/5336907/186867354-1d889dc7-f482-433e-83de-dcd3ba5b602e.PNG)

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: [e.g. iOS] win10
 - Navigateur / browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 103.0.2

**Comment by pierrejego** [comment]
Vu et reproduit en décochant la couleur s'affiche. Peut être le css en cas de sélection.
Dans tous les cas, il s'affiche dans la légende et sur la carte, cela semble être lorsque c'est la couleur noir

**Comment by pierrejego** [comment]
Dans certains cas, il ne semble pas y avoir le style associé dans la class pour i

exemple les cas qui ne marchent pas sont en : 
<i class="dateLine fas fa-minus">

alors que ceux qui marchent ont un style en plus  dans la balise
<i class="dateLine fas fa-minus" style="color: rgb(87, 165, 60);">

Je pense que ça vient d'ici : 
https://github.com/jdev-org/madDog/blob/main/mviewer/maddog/addons/maddog/js/utils/tdcUtils.js#L512
La méthode doit sortir en erreur dans certains cas, mais sans trace.

Exemple sur le 1968.06-10 -> color générée "#b4a526"  mais rien dans le style.

Du coup la couleur n'est pas remplacé et reste celle du style par défaut avant ajout de la couleur.

Je viens de passer une heure a essayer de debugger et pas à pas cette partie de JQuery .css mais forcément en pas à pas , il y a pas d'erreur....

**Comment by Gaetanbrl** [comment]
Le code Hexa de la couleur ne semble pas toujours correct.

Exemple avec ce rendu : 

![image](https://user-images.githubusercontent.com/16317988/191448791-60cbdc08-2da3-4f8a-b7e3-9912f39495ea.png)


On a les dates 28/06/2017 et 12/03/2020 qui n'ont pas de couleur. En prenant en comparaison une date qui fonctionne comme le 07/01/2018 on obtiens ces codes : 

```
KO > 28/06/2017 - #3d8b4
KO > 12/03/2020 - #32854
OK > 07/01/2018 - #a9f99d
OK > 05/07/2021 - #32ddf2
```
Dans les cas KO, le code hexa ne contient que 5 caractères, alors que les codes hexa OK en contiennent 6.

En testant les codes hexa à 5 caractères, on obtient aucun résultat sauf du noir par défaut >> C'est la couleur affichée lors du clic sur une date sans couleur.

**Comment by Gaetanbrl** [comment]
PR en attente @mrouan

**Comment by mrouan** [comment]
Problème toujours présent notamment pour les profils (ex VOUGOT : PRF1)

**Comment by Gaetanbrl** [comment]
@mrouan est-ce que le dernier commit corrige le problème ?

**Comment by mrouan** [comment]
Je viens de vérifier sur https://portail.indigeo.fr/mviewer_preprod/?config=apps/maddog.xml#
et cela ne corrige pas le problème :
![image](https://github.com/LETG/madDog/assets/5336907/13cd08aa-3515-4030-800d-2ba5156a41f6)

**Comment by Gaetanbrl** [comment]
> Je viens de vérifier

Ok merci je ne savais plus où on en été sur ce sujet

**Comment by Gaetanbrl** [comment]
Ok vu, même problème que TDC.

**Comment by mrouan** [comment]
corrigé
visible en preprod
