### ISSUE TITLE
[GENERAL] Problème de chargement de librairies -> update Mviewer

### ISSUE THREAD

**Issue by mrouan** [LETG/madDog#85]
**Description du bug / Describe the bug**

Problème connu de chargement de lib, prévoir une mise à jour du mviewer

**Comment by Gaetanbrl** [comment]
@mrouan est-ce que le lien permet de voir si cette issue est encore d'actualité en mviewer-3.10-snapshot ?

https://portail.indigeo.fr/mviewer_preprod/#maddog

**Comment by mrouan** [comment]
ce lien point vers la branch develop de mviewer et nous sommes actuellement sur le commit : https://github.com/mviewer/mviewer/commit/d3ecba8ad4b31d831b6c9c9f9fff0af3fccad15c

je ne sais pas de quelle version il s'agit.

**Comment by Gaetanbrl** [comment]
> je ne sais pas de quelle version il s'agit.

Dans la console c'est noté : 

> Mviewer version 3.10.snapshot

Tu peux avoir cette information via la console web (F12) du navigateur.

**Comment by pierrejego** [comment]
A tester en restant longtemps sur la page voir si la nav reste bloqué

**Comment by Gaetanbrl** [comment]
> A tester en restant longtemps sur la page voir si la nav reste bloqué

@mrouan est-ce que tu as un cas détaillée à suivre pour reproduire ?

**Comment by mrouan** [comment]
Je n'ai pas réussi à reproduire
